using IdentityProject.Common.Dto;
using IdentityProject.Domain.Entities;

namespace IdentityProject.Common.Mapper.MapperExtensions;
public static class MapperUser
{
    public static AppUser ToDomain(this UserDto dto)
    {
        return new AppUser
        {
            //Id is a guid autogenerated
            UserName = dto.UserName,
            Email = dto.Email,
            Name = dto.Name,
            Url = dto.Url,
            CountryCode = dto.CountryCode,
            PhoneNumber = dto.PhoneNumber,
            Country = dto.Country,
            City = dto.City,
            Address = dto.Address,
            Birthdate = dto.Birthdate,
            State = dto.State
        };
    }

    public static UserDto ToDto(this AppUser entity)
    {
        return new UserDto(entity.Id, entity.UserName, entity.Email, entity.Name, entity.Url, entity.CountryCode, entity.PhoneNumber, entity.Country, entity.City, entity.Address, entity.Birthdate, entity.State);
    }
}